# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

**Numpy** : Numerical Python

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

## 1. DataTypes & Attributes

In [4]:
# Create a 1-dimensional NumPy array using np.array()
a1=np.array([1,2,3])
print(a1)
# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2.0,3.3],[4,5,6.5]])
print(a2)
# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(a3)

[1 2 3]
[[1.  2.  3.3]
 [4.  5.  6.5]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [13]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [14]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('float64'), 6, numpy.ndarray)

In [15]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [17]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating Arrays

In [19]:
sample_array=np.array([1,2,3])
sample_array

array([1, 2, 3])

In [20]:
sample_array.dtype

dtype('int32')

In [24]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
ones.dtype

dtype('float64')

In [27]:
type(ones)

numpy.ndarray

In [29]:
zeros=np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [35]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[5, 7, 8, 1, 8],
       [6, 0, 9, 5, 4],
       [8, 0, 2, 2, 9]])

In [ ]:
np.random.random()